# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# Catppuccin Macchiato theme for lazygit
gui:
  border: rounded
  showCommandLog: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#8aadf4"  # blue
      - bold
    inactiveBorderColor:
      - "#6e738d"  # overlay0
    searchingActiveBorderColor:
      - "#eed49f"  # yellow
      - bold
    optionsTextColor:
      - "#8aadf4"  # blue
    selectedLineBgColor:
      - "#363a4f"  # surface0
    cherryPickedCommitBgColor:
      - "#494d64"  # surface1
    cherryPickedCommitFgColor:
      - "#f5bde6"  # pink
    unstagedChangesColor:
      - "#ed8796"  # red
    defaultFgColor:
      - "#cad3f5"  # text
git:
  paging:
    pager: delta --paging=never
