# Sesh Configuration
# https://github.com/joshmedeski/sesh

strict_mode = false

import = [
  "~/.config/sesh/configs/personal.toml",
  "~/.config/sesh/configs/work.toml",
  "~/.config/sesh/configs/dotfiles.toml",
]

sort_order = ["tmux", "tmuxinator", "config", "zoxide"]
blacklist = [
  "^scratch$",
  "^_"
]
dir_length = 3

[default_session]
startup_command = "nvim +GoToFile"
preview_command = "eza --all --git --icons --color=always {}"

# Windows (shared across all sessions)
[[window]]
name = "lazygit"
startup_script = "git pull && lazygit"

[[window]]
name = "roofr-dev"
startup_script = "git pull && yarn dev"
