sort_order = ["tmux", "tmuxinator", "config", "zoxide"]
blacklist = ["scratch"]
dir_length = 3


[default_session]
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Home üè†"
path = "~/"

[[session]]
name = "dotfiles üìÅ"
path = "~/.dotfiles"
windows = ["lazygit"]

[[session]]
name = "Obsidian üß†"
path = "~/obsidian-vault-kriscard/"
windows = ["lazygit"]

[[session]]
name = "Playground üß™"
path = "~/projects/playground/"

[[session]]
name = "Chris blog üìù"
path = "~/projects/christophercardoso.dev/"
windows = ["lazygit"]

# configs
[[session]]
name = "Ghostty config"
path = "~/.dotfiles/.config/ghostty/"
startup_command = "nvim config"

[[session]]
name = "neovim config"
path = "~/.dotfiles/.config/nvim"

[[session]]
name = "sesh config"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --language=toml --style=snip --color=always ~/c/dotfiles/.config/sesh/sesh.toml"

[[session]]
name = "tmux config"
path = "~/.dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --language=bash --style=snip --color=always ~/.dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "gitmux config"
path = "~/.dotfiles/.config/tmux"
startup_command = "nvim gitmux.conf"

[[session]]
name = "/ect/hosts"
path = "/etc"
startup_command = "sudo nvim hosts"

[[session]]
name = "karabiner config"
path = "~/.dotfiles/.config/karabiner"

# Work
[[session]]
name = "Roofr devüë®‚Äçüíª"
path = "~/Code/roofr-dev/roofr/"
windows = ["roofr-dev"]

[[session]]
name = "Roofr pick worktree üöß"
path = "~/Code/roofr-dev/roofr/"
startup_command = "roofr_pick_worktree"

[[session]]
name = "Roofr new worktree ‚ûï"
path = "~/Code/roofr-dev/roofr/"
startup_command = "roofr_new_worktree"

# Windows
[[window]]
name = "lazygit"
startup_script = "git pull && lazygit"

[[window]]
name = "roofr-dev"
startup_script = "git pull && yarn dev"
