# Dotfiles & Config Sessions

[[session]]
name = "dotfiles âš™ï¸"
path = "~/.dotfiles"
windows = ["lazygit"]
preview_command = "eza --tree --level=2 --icons --color=always {}"

[[session]]
name = "Ghostty config ğŸ‘»"
path = "~/.dotfiles/.config/ghostty/"
startup_command = "nvim config"
preview_command = "bat --language=ini --style=snip --color=always ~/.dotfiles/.config/ghostty/config"

[[session]]
name = "neovim config ğŸ“¦"
path = "~/.dotfiles/.config/nvim"
preview_command = "eza --tree --level=2 --icons --color=always {}"

[[session]]
name = "sesh config ğŸ”—"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --language=toml --style=snip --color=always ~/.dotfiles/.config/sesh/sesh.toml"

[[session]]
name = "tmux config ğŸ–¥ï¸"
path = "~/.dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --language=bash --style=snip --color=always ~/.dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "gitmux config ğŸ“Š"
path = "~/.dotfiles/.config/tmux"
startup_command = "nvim gitmux.conf"
preview_command = "bat --language=yaml --style=snip --color=always ~/.dotfiles/.config/tmux/gitmux.conf"

[[session]]
name = "/etc/hosts ğŸŒ"
path = "/etc"
startup_command = "sudo nvim hosts"

[[session]]
name = "karabiner config âŒ¨ï¸"
path = "~/.dotfiles/.config/karabiner"
preview_command = "bat --language=json --style=snip --color=always ~/.dotfiles/.config/karabiner/karabiner.json"
