# Personal Sessions

[[session]]
name = "Home ğŸ "
path = "~/"
disable_startup_command = true

[[session]]
name = "Obsidian ğŸ§ "
path = "~/obsidian-vault-kriscard/"
windows = ["lazygit"]

[[session]]
name = "Claude Plugins ğŸ¤–"
path = "~/projects/kriscard-claude-plugins/"
windows = ["lazygit"]

[[session]]
name = "Playground ğŸ§ª"
path = "~/projects/playground/"

[[session]]
name = "Chris blog âœï¸"
path = "~/projects/christophercardoso.dev/"
windows = ["lazygit"]

[[session]]
name = "Markly ğŸ‘¨â€ğŸ’»"
path = "~/projects/markly/"
windows = ["lazygit"]

[[session]]
name = "Projects ğŸ“‚"
path = "~/projects/"
disable_startup_command = true
