# Work Sessions (Roofr)

[[session]]
name = "Roofr dev ğŸ‘¨â€ğŸ’»"
path = "~/Code/roofr-dev/roofr/"
windows = ["roofr-dev"]

[[session]]
name = "Roofr reviews ğŸ‘€"
path = "~/Code/roofr-dev/roofr/review"
startup_command = "gh dash"
preview_command = "git log --oneline -10"

[[session]]
name = "Roofr pick worktree ğŸŒ²"
path = "~/Code/roofr-dev/roofr/"
startup_command = "~/.config/sesh/scripts/roofr_pick_worktree"

[[session]]
name = "Roofr new worktree â•"
path = "~/Code/roofr-dev/roofr/"
startup_command = "~/.config/sesh/scripts/roofr_new_worktree"
