# Work Sessions (Roofr)

[[session]]
name = "Claude Plugins Roofr ğŸ¤–"
path = "~/Code/kriscard-claude-plugins/"
windows = ["lazygit"]

[[session]]
name = "Roofr dev ğŸ‘¨â€ğŸ’»"
path = "~/Code/roofr-dev/roofr/"
windows = ["roofr-dev"]

[[session]]
name = "Roofr pick worktree ğŸš§"
path = "~/Code/roofr-dev/roofr/"
startup_command = "~/.config/sesh/scripts/roofr_pick_worktree"

[[session]]
name = "Roofr new worktree â•"
path = "~/Code/roofr-dev/roofr/"
startup_command = "~/.config/sesh/scripts/roofr_new_worktree"

[[session]]
name = "Roofr reviews ğŸ‘€"
path = "~/Code/roofr-dev/roofr"
startup_command = "~/.config/sesh/scripts/roofr_pr_review"
preview_command = "gh pr list --limit 5"
